### ISSUE TITLE
Shaded 오류도 있습니다.

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#23]
\usepackage{framed} or \usepackage{mdframed} 지정하면 오류를 고칠 수 있다고 하는데... 잘 안돼네요...ㅠㅠ

```
LaTeX Error: Environment Shaded undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.231 \renewenvironment{Shaded}
```

**Comment by choonghyunryu** [comment]
@statkclee,

환경을 타는 건가요? 저는 문제없이 작동합니다만...
예제 문서를 랜더링하는 중에 발생하는 오류지요?

혹시 어느 파일의 코드에서 발생하는 건가요?
