### ISSUE TITLE
KoPubWorld 글꼴을 otf --> ttf 통일하면 어떨까싶습니다.

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#24]
KoPubWorld 글꼴인 경우 ttf는 안그런데 otf 에는 글꼴명에 __Pro 가 붙습니다.

KoPubWorld Batang Light_Pro.otf

그리고 KoPubWorld바탕체, KoPubWorld돋움체 처럼 영한 번역도 되어... 이에 대해 통일도 필요보입니다...

패키지는 해결되었는데... 글꼴에 대해서 일단 이런 문제 없는 것으로 구현을 하고... 후에 미려한 폰트로 변경하는 과정을 거치면 어떨까도 생각했습니다.

**Comment by choonghyunryu** [comment]
@statkclee,

전자책과 같은 화면으로 보는 폰트는 TTF, 종이에 고품질로 출력하는 폰트는 OTF가 최선입니다.
그래서 일부러 OTF 폰트를 선정했습니다. 
말씀하신대로 KoPubWorld 글꼴에는 폰트 네이밍에 이슈도 기 인지하였고, 고민해서 만들었습니다.

가벼운 마음으로 extension을 만들었는데, 정리해야할 것이 너무 많습니다.
폰트를 선정하고 실제로 구현해서 결과를 확인하는데 많은 시간이 걸렸습니다.
KTUG의 멤버와 교류하면서, 최적의 해를 찾는 것도 좋은 방법 같습니다.
