### ISSUE TITLE
chap_intro_bitpublish.qmd  실행 시 경로 및 패키지 설치 문제 

### ISSUE THREAD

**Issue by youngjinkim81** [bit2r/bitPublish#28]
- here 을 통해서 아래 패키지들을 설치하는데, 

`#source(here::here("_extensions", "bitPublish", "init_environments.R")) `
`source(here::here("_extensions", _"bit2r"_, "bitPublish", “init_environments.R"))`

- 현재 bit2r 폴더 없이 **bitPublish 폴더에 init_environments.R** 파일 있음. (init_environments.R 폴더 내에 폰트 설치할 때도 마찬가지) 
- 아래 패키지들이 왜 그런지 모르겠지만 깔끔하게 설치가 안되어 별도로 설치를 해주었습니다. 

`install.packages("Cairo")`
`install.packages("hrbrthemes")`
`install.packages("extrafontdb")`
`install.packages("fontBitstreamVera")`
`install.packages("crul")`

**Comment by choonghyunryu** [comment]
@youngjinkim81,

아마도 quarto 명령어로 bitPublish를 설치하지 않으신 것 같네요.
디렉토리 경로 중에 "bit2r"가 없다면, source() 함수에서도 "bit2r"를 제거해야 합니다.

몇몇 파일에 디렉토리 경로가 있는데, 그것들도 수정하셔야 합니다.

감사합니다.

**Comment by Zeta611** [comment]
저도 처음에 README의 설명을 보고 조금 헷갈렸는데요, **기존 문서에 extension 설치하기**의 `quarto install extension bit2r/bitPublish`를 실행하셔야 합니다.

**Comment by choonghyunryu** [comment]
@Zeta611 

README를 손봐야하겠군요. 좀더 명확하게요.
@youngjinkim81님의 경우에는 회사의 보안문제로 `quarto install extension bit2r/bitPublish` 명령어가 실행되지 않아서 
github에서 파일을 다운로드해서 설치한 사례입니다. 그래서 일부 경로를 수작업으로 수정해야 했습니다.
이 정보가 Issue에 노출되지 않았습니다.

감사합니다.
