### ISSUE TITLE
chap_intro_bitpublish.qmd  실행 결과 관련 문의 

### ISSUE THREAD

**Issue by youngjinkim81** [bit2r/bitPublish#29]
1. 상단에 \usepackage  표시가 뜸 
2. 그림 번호가 생성 안됨 
<img width="1030" alt="bitpublish_error1" src="https://github.com/bit2r/bitPublish/assets/20967028/f3cedf53-cc9b-4aa9-b674-8544a409e0a0">

**Comment by choonghyunryu** [comment]
@youngjinkim81,

현재 bitPublish는 다음과 같은 방법으로 개발중입니다.

-  서책 출판을 위해서 LaTeX을 이용한 PDF 중심으로 개발하였습니다만,
-  HTML에서도 동작하는 것을 목표로 , 멀티 아웃 포맷(Multi Out Format)의 지원 작업을 진행중에 있습니다.
- 아직은 HTM에서 부족한 점이 많습니다.
- 그러나 지적하신 부분을 포함해서 HTML로도 문제없이 퍼블리싱되도록 개선해 나가겠습니다.

문제점을 지적해 주샤서, 감사합니다.

**Comment by choonghyunryu** [comment]
@youngjinkim81,

version 0.2.2 버전에서 두 가지 이슈를 해결했습니다.
"그림 번호가 생성 안됨"은 크로스-레퍼런스 이슈입니다. bitPublish 사용법을 참고하시기 바랍니다.

감사합니다.
