### ISSUE TITLE
example 예제 내부 배쉬/파이썬/R 코드 출력

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#41]
example 예제 내부 배쉬/파이썬/R 코드 출력 제대로 되지 않습니다. 저만 그런가요?

````
\usepackage{listings}

....

\addtocounter{exam_num_bitpub}{1}
\begin{example}{\ref{chap:bitpublish}.\arabic{exam_num_bitpub}}
\examplelabel{ex1}{\ref{chap:bitpublish}.\arabic{exam_num_bitpub}}

파일을 생성하는 다른 방법

`nano` 편집기를 사용해서 텍스트 파일을 생성하는 방법을 살펴봤다.
홈 디렉토리에서 다음 명령어를 실행해 보자:


\begin{lstlisting}
cd                  
touch my_file.txt
\end{lstlisting}

\end{example}
`````

**Comment by choonghyunryu** [comment]
@statkclee 

예제는 bitPublish 버전 0.2.3에서 
**Quarto에서 제공하는 정리(theorems)의 변형을 이용하는 것으로 변경**하였습니다. 
그 이유는 *멀티 아웃 포맷을 지원하기 위함*입니다. 

bitPublish의 예제 문서를 보면 사용법이 소개되어 있습니다.

위의 내용은 다음과 같이 기술하면 됩니다.


````
::: {#exr-createfile}

### 파일을 생성하는 다른 방법

`nano` 편집기를 사용해서 텍스트 파일을 생성하는 방법을 살펴봤다.
홈 디렉토리에서 다음 명령어를 실행해 보자:

```{verbatim}
cd                  
touch my_file.txt
```

:::
````

그러면 다음처럼 표시됩니다.

-  PDF

<img width="568" alt="image" src="https://github.com/bit2r/bitPublish/assets/1195558/1ca8c0aa-b38e-43a4-87df-868ba75e9064">

- HTML
<img width="775" alt="image" src="https://github.com/bit2r/bitPublish/assets/1195558/a47f3e50-22b6-4d66-9546-87d1f4082f59">

**Comment by choonghyunryu** [comment]
이 이슈는 해결되어 닫습니다.
