### ISSUE TITLE
그림 참조하는게 잘 안돼요 ㅠㅠ

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#42]
knitr::include_graphics() 명령어로 그림 참조는 가능하나 마크다운 문법으로는 왜 안될까요?

https://quarto.org/docs/authoring/figures.html#cross-references 

코드에서 나온 그래프는 문제가 없는데... 그냥 날 그림을 참조할 때 knitr::include_graphics() 으로 하는 것은 문제인듯...

```
![전형적인 쉘 프롬프트](images/prompt-grammar.jpg){#fig-elephant fig-align="center" width="298"}

@fig-elephant 에서 제시된 쉘 명령어는 `ls` **명령어**, **선택옵션** `-F`, **명령인자** `/`로 구성되어 있다.
```

![image](https://github.com/bit2r/bitPublish/assets/5325425/674d2f67-bf70-4459-88af-9426439f6ea7)

**Comment by choonghyunryu** [comment]
@statkclee 

이 기능에 대한 소개는 이미 있었으나,
요청하신대로 실제 사용 사례를 추가했습니다.
