### ISSUE TITLE
Macbook 폰트 설치 에러

### ISSUE THREAD

**Issue by youngjinkim81** [bit2r/bitPublish#45]
`quarto preview --to bitPublish-pdf` 실행 시 아래와 같은 오류가 발생하여 문의 드립니다. (혼자 찾아봐도 해결이 쉽지 않았습니다.) 

finding package for STIXTwoText-Regular(-(Bold|Italic|Regular).*)?[.](tfm|afm|mf|otf|ttf)
> 1 package to install
> installing stix2-otf (1 of 1)
**ERROR: tlmgr returned a non zero status code**

/Library/TeX/texbin/tlmgr: cannot download: download did not succeed: https://lab.uklee.pe.kr/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512

Error: tlmgr returned a non zero status code

/Library/TeX/texbin/tlmgr: cannot download: download did not succeed: https://lab.uklee.pe.kr/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512

    at Object.onComplete (file:///Applications/quarto/bin/quarto.js:98916:66)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:86653:16)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:86798:25)
    at async serveProject (file:///Applications/quarto/bin/quarto.js:103191:26)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:103747:13)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:127540:5)
    at async file:///Applications/quarto/bin/quarto.js:127558:9

**Comment by choonghyunryu** [comment]
@youngjinkim81 

언제 오프라인에 모여서 문제 해결의 방법을 찾아봐야 할 것 같습니다.
youngjinkim81님의 경우에는 quarto 명령어로 extension을 설치하신 게 아니죠?

서로의 파일 시스템의 차이점을 비교하면서 문제해결을 할 필요가 있어보입니다.
어떻게 생각들 하세요?
@youngjinkim81, @statkclee

**Comment by youngjinkim81** [comment]
@choonghyunryu 
- 네 저는 quarto 명령어로 extension을 설치하진 못했습니다. 
- 이 템플릿을 쓰기 위해 어제 윈도우 PC를 주문하긴 했지만.. ^^; 오프라인으로 해결방법을 찾는 시간이 있다면 대찬성입니다!! 

감사합니다.

**Comment by choonghyunryu** [comment]
@youngjinkim81,

이 일로 굳이 윈도우 PC를 주문하실 필요가 없을 듯합니다.

제가 보기에는 quarto로 설치하기 위해서는 
다음과 같은 리파지토리 경로에 접근합니다. (계정/리파지토리)

bit2r/bitPublish

**그리고 사용자의 PC에 다운로드하면서 bit2r라는 경로가 생겨버립니다.**

아마 영진님의 경우에는 압축 다운로드해서 풀었기 때문에 bit2r 경로가 생기지 않게 됩니다. 
그래서 해당 폰트를 찾지 못하게 됩니다.

bitPublish.tex 파일을 살펴보면 다음과 같이 해당 폰트를 참조하는 스크립트가 있습니다.

경로에 bit2r가 보이시죠? 
해결방법은  _extensions 디렉토리 안에 bit2r 디렉토리를 만들어서
현재의 `_extensions/bitPublish` 경로를 `_extensions/bit2r/bitPublish` 경로로 변경하시면 됩니다.

```
%% 라틴 셰리프
% https://github.com/stipub/stixfonts
\setmainfont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/STIXTwoText/]{STIXTwoText-Regular.otf}[%
  Ligatures=TeX,
  BoldFont=STIXTwoText-Bold.otf,
  ItalicFont=STIXTwoText-Italic.otf,
  BoldItalicFont=STIXTwoText-BoldItalic.otf
]

%% 라틴 산셰리프
% https://www.1001fonts.com/nimbus-sans-l-font.html
\setsansfont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/Nimbus Sans L/]{NimbusSanL-Reg.otf}[%
  Ligatures=TeX,
  BoldFont=NimbusSanL-Bol.otf,
  ItalicFont=NimbusSanL-RegIta.otf,
  BoldItalicFont=NimbusSanL-BolIta.otf
]

%% 한국어 셰리프
\setmainhangulfont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/KOPUBWORLD_OTF_FONTS/]{KoPubWorld Batang_Pro Light.otf}[%
  Ligatures=TeX,
  BoldFont=KoPubWorld Batang_Pro Bold.otf,
  ItalicFont=KoPubWorld Batang_Pro Light.otf,
  ItalicFeatures = {FakeSlant = 0.167},  
  BoldItalicFont=KoPubWorld Batang_Pro Bold.otf,
  ItalicFeatures = {FakeSlant = 0.167}  
]

%% 한국어 산셰리프
\setsanshangulfont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/KOPUBWORLD_OTF_FONTS/]{KoPubWorld Dotum_Pro Light.otf}[%
  Ligatures=TeX,
  BoldFont=KoPubWorld Dotum_Pro Bold.otf,
  ItalicFont=KoPubWorld Dotum_Pro Light.otf,
  ItalicFeatures = {FakeSlant = 0.167},  
  BoldItalicFont=KoPubWorld Dotum_Pro Bold.otf,
  ItalicFeatures = {FakeSlant = 0.167}  
]

%% 한자
\setmainhanjafont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/KOPUBWORLD_OTF_FONTS/]{KoPubWorld Dotum_Pro Light.otf}[%
  Ligatures=TeX,
  BoldFont=KoPubWorld Dotum_Pro Bold.otf,
  ItalicFont=KoPubWorld Dotum_Pro Light.otf,
  BoldItalicFont=KoPubWorld Dotum_Pro Bold.otf
]

%% 모노스페이스
\setmonofont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/D2Coding/]{D2Coding-Ver1.3.2-20180524.ttf}[%
  Scale=0.95,
  Ligatures=TeX,
  BoldFont=D2CodingBold-Ver1.3.2-20180524.ttf,
  ItalicFont=D2Coding-Ver1.3.2-20180524.ttf,
  ItalicFeatures = {FakeSlant = 0.167},  
  BoldItalicFont=D2CodingBold-Ver1.3.2-20180524.ttf,
  BoldItalicFeatures = {FakeSlant = 0.167}
]

%% 수식
\setmathfont[ExternalLocation=_extensions/bit2r/bitPublish/fonts/STIXTwoText/]{STIXTwoMath-Regular.otf}

```

**Comment by youngjinkim81** [comment]
@choonghyunryu  오오 알려주셔서 감사합니다! 주문 취소하겠습니다 ^^;

**Comment by youngjinkim81** [comment]
@choonghyunryu 알려주신 방식으로 폴더 생성한 후 quarto preview --to bitPublish-pdf 실행 완료하였습니다!! 정말 감사드립니다!!

**Comment by choonghyunryu** [comment]
문제가 해결된 것 같아, 이 이슈는 닫습니다.
