### ISSUE TITLE
참고문헌 reference.bib 출력 관련 

### ISSUE THREAD

**Issue by youngjinkim81** [bit2r/bitPublish#46]
다른 chapter들은 다 html rendering이 되는데, 참고문헌은 첨부와 같이 제대로 html 출력이 안되는 이슈가 있는 것 같습니다. 
![reference](https://github.com/bit2r/bitPublish/assets/20967028/bee132f1-5297-4c7c-9b34-d9fbc5f903c1)

**Comment by choonghyunryu** [comment]
@youngjinkim81 

아직은 PDF 포맷 중심입니다.
웹 포맷에서도 구현되도록 사례를 만들어 보겠습니다.

**Comment by choonghyunryu** [comment]
@youngjinkim81,

0.2.6 버전에서 문제 해결했습니다.

PDF와 달리 HTML 아웃 포맷에서는 reference.bib의 참조정보가 개별 chapter의 마지막에 위치합니다.
그러므로 기존에는 불필요한 껍데기 chapter 이름으로의 "참고문헌"이 사이드 메뉴에 출력된 것이었습니다.
