### ISSUE TITLE
초긴급 재단선 삭제하는 방법은 뭘까요? 

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#56]
출판사에서 재단선(도련선?) 삭제하고 PDF 원고 제출하라고 하는데... ㅠㅠ

<img width="899" alt="image" src="https://github.com/bit2r/bitPublish/assets/5325425/164239fd-05e7-4801-976e-d5e23860ccf0">

**Comment by choonghyunryu** [comment]
@statkclee,

- https://github.com/bit2r/bitPublish/issues/57 에 포함해서 해결
